version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd lambda
      - yarn
      - yarn test
      - cd -
  build:
    commands:
      - cat ./lambda/handler/index.js
      - cd build
      - yarn
      - yarn application:apply -auto-approve
#      - yarn application:destroy -auto-approve
#      - echo $CODEBUILD_WEBHOOK_BASE_REF
#      - echo $CODEBUILD_WEBHOOK_HEAD_REF
#      - echo $CODEBUILD_WEBHOOK_TRIGGER