version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ./utils/set_git_envs
  pre_build:
    commands:
      - cd src/lambda
      - yarn
      - yarn test
      - cd -
  build:
    commands:
      - cd build
      - yarn
      - yarn application:apply -auto-approve
      - echo $CODEBUILD_GIT_COMMIT
#      - echo $CODEBUILD_WEBHOOK_BASE_REF
#      - echo $CODEBUILD_WEBHOOK_HEAD_REF
#      - echo $CODEBUILD_WEBHOOK_TRIGGER