version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd lambda
      - yarn
      - yarn test
      - cd -
  build:
    commands:
      - cd build
      - yarn
      - yarn demo:apply -auto-approve
      - yarn demo:destroy -auto-approve