version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn
  pre_build:
    commands:
      - cd lambda
      - yarn
      - yarn test
      - cd -
  build:
    commands:
      - aws sts get-caller-identity