version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn
      - cd lambda
      - yarn
  pre_build:
    commands:
      - cd lambda
      - yarn test
  build:
    commands:
      - yarn demo:apply